### ISSUE TITLE
log off completely

### ISSUE THREAD

**Issue by estefaniaqpirg** [alternativelibraries/website#22]
once that an user is logged off from their membership/loan page, it logs of entirely from the library website. 
Should people have access to the qpirg user id/pass? or is there a way to keep it log in for users, without having to give that info?

**Comment by cfggns** [comment]
I read your email, and agree that people having the username and password for the circulation account isn't a very big deal since it doesn't give them much access. 

One thing you could try though is to get the browser (firefox or chrome, I forget which one you're using on that computer) to save the username and password for the PMB login page. That way it would already be filled out for people and they just need to click the login button. Sometimes the way it works is that they have to put in the username and then the password automatically gets filled in. You can try the different browsers and see which works best!

**Comment by estefaniaqpirg** [comment]
awesome! so people just have to click connexion, and go to the user circulation page. The qpirg info also appears there but I don't think is a big issue tho...thanks!
